language: haskell-multi-ghc

env:
 - GHCVER=7.6.3 CABALVER=1.18
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=7.10.2 CABALVER=1.22 PEDANTIC=YES
 - GHCVER=7.10.3 CABALVER=1.22
 - GHCVER=8.0.1 CABALVER=1.24
 - GHCVER=head CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=head

# Build only master (and PRs to master)
branches:
  only:
    master
